### ISSUE TITLE
Trouble with Ubuntu

### ISSUE THREAD

**Issue by zacksiri** [arekinath/erlang-pcsc#3]
I'm trying to compile this NIF and it's throwing the error that 

```
 fatal error: wintypes.h: No such file or directory
   43 | #include <wintypes.h>
      |          ^~~~~~~~~~~~
```

I already have libpcsclite-dev installed in my system but it's in /usr/includes/PCSC anyway for me to add this folder to the includes for the compile?

**Comment by arekinath** [comment]
What do you get if you run `pkg-config --cflags libpcsclite` at a shell? The `Makefile` in `c_src` uses this command to try to figure out where the includes are.

**Comment by zacksiri** [comment]
@arekinath `-pthread -I/usr/include/PCSC` but for some reason it doesn't work, maybe i need to start a new session for this to take effect?

**Comment by zacksiri** [comment]
@arekinath thank you for your help!
